### ISSUE TITLE
Falcon_sensor fact broken with falcon 6.51

### ISSUE THREAD

**Issue by tedgarb** [104ru/crowdstrike#16]
The fact is now returning parsing_error, I believe due to changes in the order the rfm and version facts are output. I am working on a fix now, I should have a PR later this morning

**Comment by rburghardt1** [comment]
I'm seeing this in falcon-sensor-6.41.0-13804.el8.x86_64 also.

**Comment by 104ru** [comment]
v1.4.4 contains suggested update and has been pushed to forge. Thanks @tedgarb!
