### ISSUE TITLE
falconctl output ordering change

### ISSUE THREAD

**Issue by ajpaul25** [104ru/crowdstrike#19]
It appears that in the latest version of falcon sensor (6.51.14812.0), the ordering of the output has changed.  This necessitates a change to the pattern used in lib/facter/falcon_sensor.rb.

Old order: aid, apd, aph, app, rfm-state, rm-reason, code, version, Sensor grouping
New order: aid, apd, aph, app, version, Sensor grouping, rm-state, rfm-reason, code

Example output: aid=\"a3c05cf2e1314477a693549b51904954\", apd=TRUE, aph is not set, app is not set, version = 6.51.14812.0\nSensor grouping tags are not set, rfm-state=false, rfm-reason=None, code=0x0,

**Comment by ajpaul25** [comment]
This appears to have been mostly resolved by 329ffdf.  I will follow up with a pull request containing a couple of small changes.

**Comment by 104ru** [comment]
Pushed the new version with the update as given above with tag v1.4.6 and respective version on forge.
