### ISSUE TITLE
Include installation token options

### ISSUE THREAD

**Issue by ghost** [104ru/crowdstrike#6]
falconctl has added --provisioning-token options.
 
`falconctl -s --cid=<CID> --provisioning-token=XXXXXXXXXXXX`

Is it possible to add it in the module as well?

**Comment by 104ru** [comment]
This is easily done. I pushed a new version [1.3.0](https://github.com/104ru/crowdstrike/tree/v1.3.0) adding this argument. Unfortunately I am not a CrowdStrike admin for our instance, so I am unable to test this code. Please test it, if you can, and let me know the result. If it works as you expect, I will push this release to Forge.

**Comment by ghost** [comment]
Thanks for the update. I've tested and works perfectly fine.
