### ISSUE TITLE
Problem with hosts that needed proxy set, but it wasn't the first time :)

### ISSUE THREAD

**Issue by davealden** [104ru/crowdstrike#8]
Hi,
  So we have some hosts that needed the proxy set, but we hadn't done so.  So now those systems think they are "registered", even though they're not able to talk to the server.  So when I fixed this (by adding the host and port to the config), they fail with the error "CID is set, but -f was not specified".  This happens every time you run puppet, so I assume it realizes that it's not really registered yet.  So we either need to not set the CID each time, or we need to add a "-f".  Thoughts on which would be better?
...dave

**Comment by 104ru** [comment]
There is a good way to resolve this edge case. falconctl can return CID in a query, I was just reluctant to expose it in a fact. Thinking about this case I am inclined to still keep the actual CID hidden, but let a fact return a flag showing whether it has been set or not. That would require a little bit of a reworking of the puppet code as well as of a fact. I'll get this done hopefully this week. Thanks for reporting the issue.

**Comment by davealden** [comment]
That's great news!  Thanks.

**Comment by 104ru** [comment]
Pushed a new version [v1.4.0](https://github.com/104ru/crowdstrike/tree/v1.4.0) to github. Please give it a go. If it works as expected, I will upload it to the forge.

**Comment by devicenull** [comment]
I can confirm that 1.4.0 fixes this issue
